# Dataset Description

- This dataset contains customer information from a bank.
- It includes customer demographics, account details, banking activity, and churn status.
- The dataset contains over 10,000 customer records and multiple numerical, categorical, and date features.
- Key attributes include Credit Score, Age, Balance, Number of Products, Account Type, and Customer Activity.
- The target variable is Exited, which indicates whether a customer has left the bank or remained active.
- The dataset also contains date columns that support time-based analysis and feature engineering.

# Business Understanding

- Customer churn is a major challenge in the banking industry.
- Understanding the factors that influence customer churn can help banks improve customer retention strategies.
- This analysis aims to identify patterns and characteristics associated with customers who leave the bank.
- The findings can help the bank take proactive actions to reduce churn and improve customer satisfaction.
- The project will explore customer demographics, financial behavior, account usage, and engagement levels to understand churn behavior.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('../data/raw/Banking dataset.csv')

In [8]:
df.head()

,Row_Number,Customer_Id,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,Num_Of_Products,Has_Cr_Card,Is_Active_Member,Estimated_Salary,Exited,Join_Date,Last_Transaction_Date,Account_Type
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,21-09-2022,23-06-2024,Savings
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,18-01-2023,10-11-2024,Current
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,06-04-2016,21-10-2023,Premium
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,17-09-2023,18-11-2024,Current
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,22-10-2022,19-11-2024,Premium

In [9]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Rows: 10100
Columns: 17

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Row_Number             10100 non-null  int64
 1   Customer_Id            10100 non-null  int64
 2   Surname                10100 non-null  str
 3   Credit_Score           10100 non-null  int64
 4   Geography              9644 non-null   str
 5   Gender                 9647 non-null   str
 6   Age                    10100 non-null  int64
 7   Tenure                 10100 non-null  int64
 8   Balance                9550 non-null   float64
 9   Num_Of_Products        10100 non-null  int64
 10  Has_Cr_Card            10100 non-null  int64
 11  Is_Active_Member       10100 non-null  int64
 12  Estimated_Salary       9645 non-null   float64
 13  Exited                 10100 non-null  int64
 14  Join_Date              10100 non-null  str
 15  Last_Transaction_Date  10100 non-null  str
 16  Account_Type           10100 non-null  str
dtypes: float64(2), int64(9), str(6)
memory usage: 1.3 MB

In [51]:
round(df.describe(),2)

,Row_Number,Customer_Id,Credit_Score,Age,Tenure,Balance,Num_Of_Products,Has_Cr_Card,Is_Active_Member,Estimated_Salary,Exited
count,10100.00,10100.00,10100.00,10100.00,10100.00,9550.00,10100.00,10100.00,10100.00,9645.00,10100.0
mean,5000.55,15690968.46,650.41,38.93,5.01,76261.11,1.53,0.71,0.52,100175.52,0.2
std,2886.96,71931.44,96.71,10.48,2.89,62494.12,0.58,0.46,0.50,57504.37,0.4
min,1.00,15565701.00,350.00,18.00,0.00,0.00,1.00,0.00,0.00,11.58,0.0
25%,2504.75,15628655.50,584.00,32.00,3.00,0.00,1.00,0.00,0.00,50974.57,0.0
50%,4998.50,15690738.00,652.00,37.00,5.00,96932.59,1.00,1.00,1.00,100442.22,0.0
75%,7502.25,15753233.75,717.00,44.00,7.00,127638.24,2.00,1.00,1.00,149402.59,0.0
max,10000.00,15815690.00,850.00,92.00,10.00,250898.09,4.00,1.00,1.00,199992.48,1.0

In [54]:
df.nunique()

Row_Number               10000
Customer_Id              10000
Surname                   2932
Credit_Score               460
Geography                    6
Gender                       2
Age                         70
Tenure                      11
Balance                   6074
Num_Of_Products              4
Has_Cr_Card                  2
Is_Active_Member             2
Estimated_Salary          9549
Exited                       2
Join_Date                 3603
Last_Transaction_Date      537
Account_Type                 3
dtype: int64

In [ ]:
numerical_columns = df.select_dtypes(include=['int']).columns
categorical_columns = df.select_dtypes(include=['object']).columns
date_columns = df.select_dtypes(include=['datetime']).columns


print("Numerical Columns:", numerical_columns)
print("\nCategorical Columns:", categorical_columns)
print("\nDate Columns:", date_columns)

Numerical Columns: Index(['Row_Number', 'Customer_Id', 'Credit_Score', 'Age', 'Tenure',
       'Num_Of_Products', 'Has_Cr_Card', 'Is_Active_Member', 'Exited'],
      dtype='str')

Categorical Columns: Index(['Surname', 'Geography', 'Gender', 'Join_Date', 'Last_Transaction_Date',
       'Account_Type'],
      dtype='str')

Date Columns: Index([], dtype='str')

C:\Users\MOHAMMED NIHAL\AppData\Local\Temp\ipykernel_17640\3654246600.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

In [ ]:
missing_values = df.isnull().sum()
missing_values_percentage = round((missing_values / len(df))* 100 , 2)

missing_data = pd.DataFrame({
    "missing_values": missing_values,
    'missing_values_percentage': missing_values_percentage
})

print(missing_data)

                       missing_values  missing_values_percentage
Row_Number                          0                       0.00
Customer_Id                         0                       0.00
Surname                             0                       0.00
Credit_Score                        0                       0.00
Geography                         456                       4.51
Gender                            453                       4.49
Age                                 0                       0.00
Tenure                              0                       0.00
Balance                           550                       5.45
Num_Of_Products                     0                       0.00
Has_Cr_Card                         0                       0.00
Is_Active_Member                    0                       0.00
Estimated_Salary                  455                       4.50
Exited                              0                       0.00
Join_Date                           0                       0.00
Last_Transaction_Date               0                       0.00
Account_Type                        0                       0.00

In [71]:
print("duplicates rows : " , df.duplicated().sum())

duplicates rows :  100

In [81]:
print("Geography:", df['Geography'].unique())
print("\nGender:", df['Gender'].unique())
print("\nAccount_Type:", df['Account_Type'].unique())

Geography: <StringArray>
['France', 'Spain', 'Germany', nan, 'Spain ', 'France ', 'Germany ']
Length: 7, dtype: str

Gender: <StringArray>
['Female', 'Male', nan]
Length: 3, dtype: str

Account_Type: <StringArray>
['Savings', 'Current', 'Premium']
Length: 3, dtype: str

#  Data Quality Issue Log

- Missing values found in:

  - Gender
  - Geography
  - Balance
  - EstimatedSalary

- Duplicate records are present in the dataset.
- Geography column contains formatting inconsistencies (extra spaces).
- Join_Date and Last_Transaction_Date are stored as object (string) datatype.
- Date columns require datatype conversion to datetime format.
- Identifier columns (Row_Number and Customer_Id) are not useful for analytical modeling.
- Data cleaning and preprocessing are required before performing detailed analysis.

# Initial Observations

- Dataset contains 10,100 customer records.
- Dataset contains numerical, categorical, and date variables.
- Missing values are present in multiple columns.
- Duplicate records exist and require removal.
- Date columns support time-based analysis.
- Customer churn is represented by the Exited column.
- Geography and Account Type provide useful customer segmentation.
- Dataset is suitable for univariate, bivariate, and statistical analysis.